#!/usr/bin/env python
from werkzeug import run_simple

from ponodo.core import handle_application

# import os
# os.environ['PYTHONBREAKPOINT'] = "functools.partial(IPython.embed, colors='neutral')"

if __name__ == "__main__":
    run_simple(
        "localhost",
        4000,  # todo: configurable port
        application=handle_application,
        use_reloader=True,
        use_debugger=True,
        reloader_type="watchdog",
    )
