#!/usr/bin/env python
from werkzeug import run_simple

print("hahah")


def app():
    print("app")


run_simple(
    "localhost",
    4000,
    application=app,
    use_reloader=True,
    use_debugger=True,
    reloader_type="watchdog",
)
